### ISSUE TITLE
Decoding array of arrays

### ISSUE THREAD

**Issue by oronbz** [ikesyo/Himotoki#174] opened 2017-03-28 15:28 UTC
Hi,
I have an issue decoding array of arrays,
how would you write a decode function which decode a JSON like this:
```
"summary": {
  "items": [[0], [1], [2]]
}
```

I've tried writing a struct like this:
```
struct Summary {
  let items: [[Int]]
}
```

and an extension:

```
extension Summary: Decodable {
  static func decode(_ e: Extractor) throws -> Summary {
    return try Summary(items: e <|| "items")
  }
}
```

but I'm getting an error:
`Type '[Int]' does not conform to protocol 'Decodable'`

I know the JSON could be built better but this is what I'm getting from the server and this is what I have to decode.

Thanks,
Oron

**Comment by toshi0383** [comment] 2017-04-01 01:09
I ended up writing this code.

```swift
infix operator <||<|| : MultiplicationPrecedence

/// - Throws: DecodeError or an arbitrary ErrorType
public func <||<|| <T: Decodable>(e: Extractor, keyPath: KeyPath) throws -> [[T]] {
    let json: [String: Any] = try castOrFail(e.rawValue)
    let array: [Any] = try castOrFail(json[keyPath.components.joined(separator: ".")])
    return try array.map { c -> [T] in
        return try castOrFail(c)
    }
}
```

I would add this to your App, rather than to Himotoki. I think it's better to keep the core code small.

I also needed to add Optional version of `castOrFail` to suppress the warning that says `Expression implicitly coerced from 'Any?' to Any`.

```swift
public func castOrFail<T>(_ any: Any?) throws -> T {
    guard let result = any as? T else {
        throw typeMismatch("\(T.self)", actual: any)
    }
    return result
}
```

So now you can do this.

```swift
extension Summary: Decodable {
  static func decode(_ e: Extractor) throws -> Summary {
    return try Summary(items: e <||<|| "items")
  }
}
```

**Comment by ikesyo** [comment] 2017-04-01 01:26
Sorry for the late response, and thanks to @toshi0383 for sharing your way!

Seems that this is a duplicate of #149 and I'd rather write something like this: https://github.com/ikesyo/Himotoki/issues/149#issuecomment-247234104.

**Comment by toshi0383** [comment] 2017-04-01 03:15
Wow, that looks neat😮

**Comment by oronbz** [comment] 2017-04-01 10:08
Thank you both guys, I'll have a look at both solutions

**Closed as completed** 2017-05-27 09:17 UTC
Labels: question
